services:
  currencyrates:
    image: ${DOCKER_REGISTRY-}currencyrates
    build:
      context: .
      dockerfile: CurrencyRates/Dockerfile
    ports:
      - "7166:7166"
    environment:
      - ASPNETCORE_URLS=https://+:7166
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Database=currency_rates;Username=postgres;Password=password
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: currency-db
    environment:
      - POSTGRES_DB=currency_rates
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: